import { StyleSheet } from "react-native";
import { DAY_SIZE, SCREEN_WIDTH } from "./constants";

export const calenderStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  trigger: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 2,
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingVertical: 16,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  triggerText: {
    fontSize: 17,
    flex: 1,
    fontWeight: "600",
    letterSpacing: 0.3,
  },

  controlsContainer: {
    gap: 16,
    marginBottom: 24,
  },

  switchContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 20,
    paddingHorizontal: 20,
    borderRadius: 16,
    borderWidth: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  switchLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  switchLabel: {
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: 0.3,
  },

  // Mode Selector
  modeSelector: {
    padding: 20,
    borderRadius: 20,
    borderWidth: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  modeSelectorHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 10,
  },
  modeButtons: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  modeButton: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  modeButtonText: {
    fontSize: 14,
    fontWeight: "600",
    letterSpacing: 0.4,
  },

  searchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 2,
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingVertical: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  searchIcon: {
    marginRight: 12,
  },
  clearIcon: {
    marginLeft: 12,
    padding: 6,
  },

  sheet: {
    padding: 24,
    paddingBottom: 40,
  },
  sheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    paddingBottom: 24,
    borderBottomWidth: 2,
    borderBottomColor: "#262626",
    paddingHorizontal: 4,
  },
  sheetTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
    marginRight: 16,
  },
  sheetTitle: {
    fontSize: 20,
    fontWeight: "800",
    letterSpacing: 0.5,
    flexShrink: 1,
  },
  sheetActions: {
    flexDirection: "row",
    gap: 8,
    flexShrink: 0,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  clearButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  clearButtonText: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  actionIcon: {
    marginRight: 6,
  },

  calendarContainer: {
    paddingBottom: 20,
  },
  viewContainer: {
    paddingBottom: 20,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    paddingHorizontal: 4,
  },
  navButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  monthYearButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  monthYearText: {
    fontSize: 19,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  daysHeader: {
    flexDirection: "row",
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  dayHeaderText: {
    width: DAY_SIZE,
    textAlign: "center",
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 1,
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 2,
  },
  dayCell: {
    width: DAY_SIZE - 2,
    height: DAY_SIZE - 2,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
    margin: 1,
  },
  dayText: {
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: 0.2,
  },

  monthGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    gap: 12,
  },
  monthCell: {
    width: "30%",
    height: 56,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 14,
    marginBottom: 16,
    borderWidth: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  monthText: {
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.3,
  },

  filterContainer: {
    marginBottom: 24,
    paddingHorizontal: 4,
  },
  filterInput: {
    flex: 1,
    paddingVertical: 16,
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  yearGridContainer: {
    flex: 1,
    maxHeight: 400,
  },
  yearGridContent: {
    paddingVertical: 12,
    paddingHorizontal: 8,
  },
  yearRow: {
    justifyContent: "space-between",
    paddingHorizontal: 8,
  },
  yearCell: {
    width: (SCREEN_WIDTH - 120) / 3,
    height: 64,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 14,
    marginBottom: 12,
    borderWidth: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  yearText: {
    fontSize: 17,
    fontWeight: "700",
    letterSpacing: 0.3,
  },

  timePickerContainer: {
    marginTop: 28,
    paddingTop: 28,
    borderTopWidth: 2,
    borderTopColor: "#262626",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  timePickerHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    gap: 12,
  },
  timePickerLabel: {
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  timePickerRow: {
    flexDirection: "row",
    gap: 16,
  },
  timePicker: {
    flex: 1,
  },
  timePickerTitle: {
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 12,
    textAlign: "center",
    letterSpacing: 0.8,
  },
  timePickerScroll: {
    maxHeight: 160,
  },
  timePickerOptions: {
    maxHeight: 160,
  },
  timeOption: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginBottom: 8,
    alignItems: "center",
    borderWidth: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  timeOptionText: {
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
});
